.\" Copyright (c) 2016 Aaron Poffenberger <akp@hypernote.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: Jul 10 2016 $
.Dt LPF_GS 1
.Os
.Sh NAME
.Nm lpf_gs
.Nd printer filter to convert Postscript to PCL
.Sh SYNOPSIS
.Nm lpf_gs
.Bk -words
.Op Fl cdhijlnvw
.Op Fl h Ar host
.Op Fl i Ar indent
.Op Fl j Ar job
.Op Fl l Ar length
.Fl n Ar user
.Op Fl w Ar width
.Ar acct-file
.Ek
.Sh DESCRIPTION
.Nm
is an
.Xr lpd 8
accounting filter that takes a PostScript, PDF or text file via stdin
and converts it to an output format based on the calling name of the
program using Ghostscript. Accouting information is logged to
.Ar acct-name.
.
.Pp
.Nm
is based on the default
.Xr lpd 8
accounting filter
.Xr lpf Ns
, though written in
.Xr sh 1
rather than C.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Provided for backwards compatibility. Ignored.
.It Fl d
Enable debug.
.It Fl h
Print to the
.Ar host
(ip or hostname) specified.
.It Fl i
Provided for backwards compatibility. Ignored.
.It Fl j
.Ar job
name to use when logging.
.It Fl l
Provided for backwards compatibility. Ignored.
.It Fl n
.Ar user
who printed the job.
.It Fl v
Print the version.
.It Fl w
Provided for backwards compatibility. Ignored.
.Ss CREATING ACCOUNTING FILTERS
Accounting filters are created by making a symlink to
.Nm
and then setting the text filter to the name of the file created as a
symlink to
.Nm .
.Pp
The calling name of the filter must be in the form of
.Sy lpf_ Ns Ar device
where
.Ar device
is an output
.Ar device
known by Ghostscript.
.Em E.g. Ns ,
lpf_pxlmono.
.Pp
Using the calling name is necessary because
.Xr printcap 5
definitions only allow specifying the accounting filter path and name.
The few parameters sent to the filter are specified and sent by
.Xr lpd 8 Ns .
Using the calling name to specify the output device works around this
limitation.
.Pp
In most cases just a couple of links are required. Most printers
accept one or more of just a few printer-control languages (PCLs) or
page-description languages (PDLs).
.Pp
The most common are:
  ASCII + control flow (dot-matrix and line printers)
  PCL (typically PCL3 - PCL6)
  PostScript
.Pp
Check your printer manual for details about which PCLs or PDLs your
printer accepts.
.Sh FILES
.Bl -tag -width "/path_to_lpf_device/gs_init" -compact
.It Pa /path_to_lpf_device/gs_init
Postscript configuration file read by
.Nm
if found in the same directory as the symlinked filter.
.Pp
.Em cf
Ghostscript documentation for more details about using gs_init.
.El
.Sh EXIT STATUS
.Nm
utility exits with one of the following values:
.Bl -tag -width Ds -compact
.It 0
.Nm
printed successfully.
.It 1
Errors were detected. Try again.
.El
.Sh EXAMPLES
To use an
.Xr lpd 8
definition with
.Nm
you'll need an entry in the system
.Xr printcap 5
file specifying the accounting filter.
.Pp
.Bd -literal
  lp|local line printer:\\
	af=/var/log/lpd-acct:\\          # accounting file (optional)
	if=/usr/local/bin/lpf_pxlmono:\\ # a link to lpf_<device>
	lf=/var/log/lpd-errs:\\          # error log
	lp=9100@192.168.68.10:\\         # printer raw port
	mx#0:\\                          # turn-off max file size
	sd=/var/spool/output/lpd:\\      # spool directory
	sh:                             # suppress burst-page header
.Ed
.Pp
The definition above will convert the input print job to PCL 6
(monochrome), which many printers will accept.
.Pp
The "lp:9100@192.168.68.10" line directs
.Xr lpd 8
to send the output of the accounting filter to port 9100 on the remote
system.
.Pp
Port 9100 is a common port for printers to listen for raw
streams. Port 515 is the default port for
.Xr lpd 8
services which may have their own accounting filters which may convert
the file in unexpected ways.
.Pp
Use a remote
.Xr lpd 8
only when you're sure the remote server can process the file and use
.Xr lpr 8
with an appropriate
.Xr printcap 5
entry.
.Pp
A list of available output devices can be found by executing gs -h.
.Em E.g. Ns , the following command creates a link to
.Nm
that converts from postscript to PCL 6.
.Bd -offset '	'
ln -s /usr/local/bin/lpf_gs /usr/local/bin/lpf_pxlmono
.Ed
.Pp
.Ns ( Sy N.B.
.Em pxlcolor
works for PCL 6 color printers.)
.Pp
In addition to converting input formats, because it's an accounting filter,
.Nm
can log accounting information if given an accounting file to log to in the
.Xr printcap 5
definition.
.Pp
Lastly, to print to text files see the documentation for
.Xr a2ps 1
or
.Xr enscript 1 Ns .
.Sh DIAGNOSTICS
.Nm
depends on Ghostscript
.No ( Xr gs 1 Ns )
to work.
.Nm
will fail if Ghostscript cannot be found.
.Pp
.Nm
will check whether
.Xr gs 1
supports the
.Ar device
specified in the name of the symlink and will fail if the device is not supported.
.Sh SEE ALSO
.Xr a2ps 1,
.Xr enscript 1,
.Xr gs 1 ,
.Xr lpq 1 ,
.Xr lprm 1 ,
.Xr pr 1 ,
.Xr symlink 2 ,
.Xr printcap 5 ,
.Xr lpc 8 ,
.Xr lpd 8
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was written by
.An Aaron Poffenberger Aq Mt akp@hypernote.com .
.Sh BUGS
.Xr lpd 8
accepts the following return codes:
  -1 non-recoverable error
   0 success
   1 try again
   2 success but with some errors
.Pp
The exit command in
.Xr sh 1
only allows values ranging from 0 - 255.
.Nm
exits with 1 for all error conditions and prints an error message to
stderr. However, this doesn't seem to be a problem.
.Xr lpd 8
tries 3 times and aborts if it doesn't receive 0 or 2.
